# Generated by Django 2.1.5 on 2019-02-01 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cart',
            field=models.ManyToManyField(blank=True, related_name='cart', to='products.Product'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='purchased',
            field=models.ManyToManyField(blank=True, related_name='purchased', to='products.Product'),
        ),
    ]
