# Generated by Django 2.1.5 on 2019-02-01 07:38

from django.db import migrations, models
import djongo.models.fields
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('attributes', djongo.models.fields.EmbeddedModelField(model_container=products.models.Attributes, null=True)),
                ('sku', djongo.models.fields.EmbeddedModelField(model_container=products.models.StockKeepingUnit, null=True)),
                ('image', models.ImageField(default='default_product.jpg', upload_to='products')),
            ],
        ),
    ]
